version: '2'
services:
  web:
    build: .
    env_file:
      - .env
    command: node ./bin/www.js
    volumes:
      - .:/server/
      - /server/node_modules
    ports:
      - "8082:8080"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/nativeReactDemo
  mongo:
    image: mongo:4.0.2